name: Build and Deploy Docker Image

on:
  push:
    branches:
      tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Copy Docker image to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        rm private_key